services:
  backend:
    build:
      context: ./Backend
      dockerfile: ./backend.dockerfile
    ports:
      - 6886:6886
    networks:
      chatbot_tornado:
        ipv4_address: 172.38.0.2
  frontend:
    build:
      context: ./Frontend
      dockerfile: ./frontend.dockerfile
    ports:
      - 6885:6885
    depends_on:
      - backend
    networks:
      chatbot_tornado:
        ipv4_address: 172.38.0.3
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      chatbot_tornado:
        ipv4_address: 172.38.0.4
networks:
  chatbot_tornado:
    external:
      name: chatbot_tornado
    