services:
  backend:
    build:
      context: ./Backend
      dockerfile: ./backend.dockerfile
    ports:
      - 6886:6886
    networks:
      chatbot_tornado:
        ipv4_address: 172.38.0.2
  frontend:
    build:
      context: ./Frontend
      dockerfile: ./frontend.dockerfile
    ports:
      - 6885:6885
    depends_on:
      - backend
    networks:
      chatbot_tornado:
        ipv4_address: 172.38.0.3
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      chatbot_tornado:
        ipv4_address: 172.38.0.4
  text_generation:
    image: ghcr.io/huggingface/text-generation-inference:1.4
    ports:
      - 6884:6884
    expose:
      - 6884
    volumes:
      - ./model/data:/data
    gpus: all
    model_id: ./model/
    networks:
      chatbot_tornado:
        ipv4_address: 172.38.0.5
networks:
  chatbot_tornado:
    external: true
    name: chatbot_tornado
    